// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Initiative {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  initiative_type:
    | "exploration"
    | "research_axis"
    | "working_group"
    | "project"
    | "program";
  summary?: string;
  description?: PortableTextBlock[];
  status_label: "exploring" | "active" | "paused" | "completed" | "archived";
  steward_name?: string;
  start_date?: string;
  related_articles?: string;
  related_publications?: string;
  related_tools?: string;
  related_people?: string;
  graph_visible?: boolean;
  graph_priority?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content_type: "essay" | "news" | "tool_announcement" | "team_note";
  content?: PortableTextBlock[];
  excerpt?: string;
  featured_image?: {
    id: string;
    src?: string;
    alt?: string;
    width?: number;
    height?: number;
    provider?: string;
    previewUrl?: string;
    meta?: Record<string, unknown>;
  };
  featured_image_alt?: string;
  featured_image_caption?: string;
  featured_image_license?: string;
  author_name?: string;
  source_title?: string;
  source_url?: string;
  content_license?: string;
  content_license_url?: string;
  related_publications?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Publication {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  publication_type:
    | "research_paper"
    | "preprint"
    | "report"
    | "whitepaper"
    | "book"
    | "dataset_paper";
  summary?: string;
  abstract?: string;
  editorial_note?: PortableTextBlock[];
  publication_authors: string;
  venue?: string;
  publication_date?: string;
  doi?: string;
  arxiv_id?: string;
  source_title?: string;
  source_url?: string;
  pdf_url?: string;
  license?: string;
  related_articles?: string;
  related_tools?: string;
  graph_visible?: boolean;
  graph_priority?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Tool {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  description?: PortableTextBlock[];
  tool_url?: string;
  repository_url?: string;
  github_data?: unknown;
  github_synced_at?: string;
  github_sync_error?: string;
  documentation_url?: string;
  license: string;
  privacy_note: string;
  technical_maturity:
    | "prototype"
    | "experimental"
    | "active"
    | "stable"
    | "archived";
  editorial_confidence:
    | "observed"
    | "promising"
    | "used_by_temis"
    | "recommended"
    | "needs_review";
  featured_image?: {
    id: string;
    src?: string;
    alt?: string;
    width?: number;
    height?: number;
    provider?: string;
    previewUrl?: string;
    meta?: Record<string, unknown>;
  };
  screenshot_url?: string;
  screenshot_alt?: string;
  screenshot_caption?: string;
  screenshot_license?: string;
  related_articles?: string;
  related_publications?: string;
  related_people?: string;
  graph_visible?: boolean;
  graph_priority?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    initiatives: Initiative;
    pages: Page;
    posts: Post;
    publications: Publication;
    tools: Tool;
  }
}
